requirements = [
    {
        'name': 'setuptools',
        'dist': 'pypi',
        'url': 'http://pypi.python.org/pypi/setuptools',
    }, {
        'name': 'pbs-trunk',
        'package': 'pbs',
        'dist': 'svn',
        'url': 'http://collab.pbs.org/svn/web/pbs/trunk',
    }, {
        'name': 'python-dateutil',
        'dist': 'pypi',
        'rev': '1.4.1',
        'url': 'http://pypi.python.org/pypi/dateutil',
    }, {
        'name': 'notabs',
        'package': '',
        'dist': 'local',
    }, {
        'name': 'django-1.0-bugfix',
        'dist': 'svn',
        'url': 'http://code.djangoproject.com/svn/django/branches/releases/1.0.X',
    }, {
        'name': 'basic',
        'package': '',
        'dist': 'svn',
        'url': 'http://django-basic-apps.googlecode.com/svn/trunk',
    }, {
        'name': 'jellyroll-trunk',
        'package': 'jellyroll',
        'dist': 'git',
        'url': 'git://github.com/jacobian/jellyroll.git',
    }, {
        'name': 'django-tagging',
        'package': 'tagging',
        'dist': 'svn',
        'url': 'http://django-tagging.googlecode.com/svn/trunk',
    }, {
        'name': 'django-threadedcomments',
        'package': 'threadedcomments',
        'dist': 'svn',
        'url': 'http://django-threadedcomments.googlecode.com/svn/trunk/',
    }, {
        'name': 'docutils',
        'dist': 'pypi',
        'url': 'http://pypi.python.org/pypi/docutils',
    }, {
        'name': 'pygments',
        'dist': 'pypi',
        'url': 'http://pypi.python.org/pypi/Pygments',
    },
]
